### ISSUE TITLE
Mute or remove console warnings?

### ISSUE THREAD

**Issue by sn3p** [DefactoSoftware/cell-js#1]
We keep getting these warning in the console:

<img width="735" alt="screen shot 2017-10-04 at 01 03 00" src="https://user-images.githubusercontent.com/935529/31153210-159e5a88-a8a0-11e7-8658-e896b05d0940.png">

But everything seems to be working fine. Can we mute or remove these?

https://github.com/DefactoSoftware/cells-js/blob/5c01c36bfef24e10b9ff050484e219633afdb5c3/src/Builder.js#L96

**Comment by sn3p** [comment]
@jessedijkstra any clue why we are getting these warnings?

**Comment by jessedijkstra** [comment]
Because the DOM attributes are present to make a cell, but the javascript isn't. I think I in the newest release these are muted.

**Comment by sn3p** [comment]
Nope, still there:

https://github.com/DefactoSoftware/cell-js/blob/ed90da47c15be10dbccb26d94ab124f03874d1cd/src/Builder.js#L96
